language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

# Thanks to Meltdown, we need this -- cf. https://github.com/travis-ci/travis-ci/issues/9061
sudo: required

